### PR TITLE
Introduced zoom functionality using Magnifier.js

### PR DESCRIPTION
**Pull request by AnwarElbo**
I also needed to tweak magnifier.js a bit to make it work properly. I tested it and it seems to do its job. Let me know if something is missing.

### CODE REVIEW

**Comment by imcvampire** [comment]
@AnwarElbo Can you update README?

**Comment by AnwarElbo** [comment]
@imcvampire Will do

**Comment by imcvampire** [comment]
@AnwarElbo I think you should add `this.magnifier = null` to `beforeDestroy` hook to let GC works

**Comment by pexea12** [comment]
image

Turning on zoom mode creates a problem with the lightbox. The CSS styles seem to be broken when I hover my mouse over the image

**Pull request closed without merging**
