### PR TITLE
Hide next and prev buttons if there's only one image

### PR DESCRIPTION
**Pull request by krystalcampioni**
Relates to #24

### CODE REVIEW

**Comment by imcvampire** [comment]
Tks for your contribution!

**Comment by krystalcampioni** [comment]
@imcvampire Thank you guys for maintaining this package :)

**Comment by webdevnerdstuff** [comment]
Please update your package version as this merged code was made after the last package update, so we can't get this updated code. Thank you.

**Comment by pexea12** [comment]
I have updated the package on NPM.

**Comment by webdevnerdstuff** [comment]
Thank you!

**Pull request merged**
